apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv
  template:
    metadata:
      labels:
        app: conv
    spec:
      volumes:
      - name: conv-data
        persistentVolumeClaim:
          claimName: conv-pvc
      containers:
        - image: docker.io/gauravity4356/conv-prod:latest
          imagePullPolicy: Always
          name: conv
          volumeMounts:
            - mountPath: /share
              name: conv-data
          ports:
          - containerPort: 8080
          env:
          - name: SHARE_PATH
            value: /share
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: gaurav-pg-app
                key: dbname
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: gaurav-pg-app
                key: port
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: gaurav-pg-app
                key: username
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: gaurav-pg-app
                key: host
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: gaurav-pg-app
                key: uri
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gaurav-pg-app
                key: password
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: conv-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/convert-share
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conv-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: conv-pv
