apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: listmonk
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://th0th.github.io/helm-charts
    chart: listmonk
    targetRevision: 5.0.3-3
    helm:
      releaseName: listmonk
      values: |
        postgres:
          existingSecret: pg-creds

  destination:
    server: https://kubernetes.default.svc
    namespace: listmonk

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
