---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-creds
  namespace: listmonk
spec:
  encryptedData:
    db_password: AgCQpSnK33PlHDnY3T7SgBK8c5XSuPu/GYX8bx0BGsYeQk1+S6LYNJnEHVKqfre3CTqj44tkoEmUeY8qOBzAwh8gcq5C2TZQecY8zk6ANiik56kmRowENK+tncNsG/152RGobd34/CBnTXLpUcd0UKUGdph7j96AFtqnGdPCkryingiD1X/2t9OPIuQoA22DGtx9Ui+/n323Z8Y9WHkDt46NKtSoGY9scp9Rd9CQCJM3XqnF8vRrT7SFwtzvspw6/a0a3r+XBaynMVkyNzs5N7E3Z/AGjV3T6LC1fRSYrJL0BdfVxagh2t2QXglZwjYg24BI8Zcn8iBQPCwNTisb4xSOU+2DFfJHNwpVddwGEJmEls1NPA4oqjTHyV0NJUd/iIUTuR+Hn0xuzAGo76mI7nxaTwVfv0LqSFWnlNoVV6Rs7Yl6raika7vvA9fVKQ10HBTYL5584NahGeUNh+YIBrEEyhANflE/JiO/se2vnliAV0Kl2kndEP7ioYcbf+8rR75pPKoaNiYThA6EGLScedM4q99qBhHHjNbWyZ/A7xyCPzfgrH8iKSN5TN2QHRuUXgYEvAWb85wis1fummqUlre7RgqSJ015y8y3xEUHXf47F5fV+ojKjuivRCjZUiFilL7fHXOHOYXWAi9FyqcTNYhqhg4/GAmdB+uNyomo+NAVtSzL249Smxyh8nUWdBCOAtvVbPjxkg==
    db_user: AgBSnvjBasgJL8vEURZzIgCEpMCPusr2kTfcqgjshjqrxkesKa7RN9LIdh0YuMucbYWkJFPiFI0oR5jTH5P24ExQ+ruUbEnpnxRSKSrC9Mz07BV+0Rt2ebIQd+y6sy/z/UKRVHiowa9cQjokVzxinzYxefPVbj9XbVg26yoZt4Px2I8z5abYYQ5ZHJQ5WcsZxOh5ATKLw49gyFJnrFR9GDG7okcUMYqJ2Rs3etDxiMynhN8aAssgtzlW/J4FMtKnTxPhgDPLKRxdZHv82ZKqlObwLfhCLWL732WjQjq9AJDG+YU6qaFIIZ2D57lRkeBmLeCJFplq87YVCaUdad1AY/2hqYRI9GdvW4PmY+AP9+P8mVZOuIp+nlvoXxskaogfPdMUWCQ8Gcbinibo6GggY9vsIAQVUpjTgU/1p6q+82yFDxOn+yxTYlFwk7iu7JsO6ZEYNPR7nX7BynixI3OmLJlDqdEU6Bqy+qVfAt+GaplbGfznIAXA9tSfkqMzzdarkrFRUuUMBl2et6Vrj426sOBNLKlUslOyHgN+EsxRGHnq71RWFlYsf7xOs8wn0RKFQS2Is2lsg0gJFz5AqR16U8dgkxHk9R3rTWXEBS2nzWhCwnq+hmgAfAYUkq0/QkJT3zQI4lFy1YR9LNUwJaF7W3ORoOpegTjUVBqQfz2hBVwkXOr49g12Svpz6sHwTlyanmue18MkC8QOlg4=
  template:
    metadata:
      name: pg-creds
      namespace: listmonk
