---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: signing-key
  namespace: default
spec:
  encryptedData:
    key: AgAWe03PlGxyPhjlDPFiu9MqTr7KQd1E6SRxYPQO01tHu9Ga1YI+S9Tujfb3KDWjmbN7Zee64MwKOmCdA8HxnMaQ6XkCjVSmSJY/moGLwfOYktBd/QeoDwGd0Mc0N/pcY3gfj+6wzf2YOGn6E1xKacoQAQDjMpgUy2JGz6yI7yu7rnjU+zMETxT6zgw+hm1kfMkC897pKxZ3YMUr4xHiL5Piz2+/La4EEm3KqgmSfYti56cufPU6lesPEKr+kpeMREbn9rohDhmmevYHchxCymjIOClQ3MrUu6nouc/HLlEC44s7vx8VPbTuvl1p8PdMKOVBjNrq2djvO5t+KFrMlfJdHXnc3W/pQrW5bKzyZ/34/q9d2Q1ZT6Who+wADhMWcCZsMYslFEQ9hN6+SctG+jCa1nb7K0tnlZiP9e34u3UiYwPsXvIzdnRRCldKIFowzjhnD3ZZEeaHTfne2y5eGhWfdLJcXP5ww5kveoj6YY3IRdG71T6E2tPJaJaQ7KnbacJghirKKY5NTFCz6lFVsHwLBq7AEOzY92W52Y53RSwOkk4HBhj2EISoVxEJmitIua4gaK1AfeJyMpShHp3tI7OGApRmvxTQtFo8rbPXb12QVAqiYXUDXXZN8AIlTRDB/tFXI1nMgZxlLr1EqTuJt9J04BA9jAY4k8nDxD+qYu4ORLw9/RN4r4Crp31iGSxbPNTnGHOntTQ/m6tZkfJL92adyLKdsq9HzDNYvlFrA0lWHYyPBwcWPpJiv8ArDn8Bf0NJMlyUmqKQ3Z9MP2SX7dAxbDatcFGX9UL0qHZHOZvTg9aj+zY4UQoPWO5oylAd051KC3Qry8tPXBgSof2qafHsj6BRQzc9trR2imunjF+tKTRsLEv9XxgKoR0RvO1alNfst9E86YpFrhbXrZQYD7/STl/tmVNpN+VIayOLHKUlmDRO33PknuC2HS/XD4vmmtPNvW861kUJUlVkItZ3zR8bJeS66+dDX7EDRECyIx8WEV6VkHrkB76Ay/af7KI+SBCv5rkYIM9Zf0Ef6lrwBJxUwmxFaJgW2o1iw03rMvki1J8VGp+q9l24RBl4QGRH6JgkQQMU8b4=
  template:
    metadata:
      name: signing-key
      namespace: default
